# This is a basic workflow to help you get started with Actions

name: test build linux macos

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"] # must use str, not int, or 3.10 will be recognized as 3.1
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: build doc
        id: build_doc
        run: |
          pip3 install setuptools
          pip3 install teedoc
          if [ -d "~/.local/bin/" ];then
            export PATH=~/.local/bin/:$PATH
          fi
          teedoc install
          teedoc build

